### ISSUE TITLE
script updated

### ISSUE THREAD

**Issue by jesus2099** [gera2ld/Violentmonkey-oex#33]
This is a suggestion, maybe it would be nice to have a info box (smae kind as the no grant warning box) that would briefly show up when the daily update check has found some updated scripts. It would present the list of updated scripts.

**Comment by jesus2099** [comment]
Hello @gera2ld. I’m back in this ticket after much time using your great extension.
In fact it’s true that this feature is maybe not so useful.

I just wish we would have more info as to when is the auto-check for update is performed (is it once a day?), maybe with a _loading_ badge on the extension button ?

Also on the same topic (check all updates), I always wonder if it’s OK to close the extension window just after clicking the *check all updates* button ?
BTW, if the update checks can perform while window is closed, maybe this button could also be there in the extension popup menu, it could be handy to force updates without opening extension window.

Sorry if I bore you…

**Comment by gera2ld** [comment]
The script update is designed to work in the background without bothering the users, so **it doesn't matter even if you close the options page**. And the status messages will be shown whenever you open the options page at the time of updating.

Auto-check happens **every 24 hours since last check-all-updates** by default. So if you have clicked on check all, the next auto-check will be delayed to 24 hours later. An auto-check is actually the same as a check-all-update click.

The popup menu is designed to show scripts run on current tab and facilitates operations on those scripts. The updates are and (I think) should be checked silently and there is no necessity to click manually on a button often. So I don't it's necessary to put check-all-update on a popup menu.

**Comment by jesus2099** [comment]
I like your approach, indeed… :)
